### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by heitorPB** [nhoizey/jekyll-postfiles#17]
There are four things needed for a plugin to be added to the Github Pages:

-    The plugin is useful for a vast majority of users
-    The plugin is available as a gem
-    The plugin is covered with an extensive test suite
-    The plugin is actively maintained

This plugin is a useful gem that is actively maintained. It only needs to be covered with a test suit. You have any plans for adding some tests?

**Comment by nhoizey** [comment]
Well, I wouldn't say it is actively maintained, I'm really late with open issues and pull requests. 😥

Do you really think this plugin is "useful for a vast majority of users"?

**Comment by DirtyF** [comment]
1. I don't know of any third party jekyll plugin added to Github Pages. Forget about it.
2. You can now build a jekyll site using any plugin on Github Pages through Github Actions.

**Comment by nhoizey** [comment]
I just discovered Github Actions can help host any Jekyll site on Github Pages, that's nice!

I agree having a test suite would be better, anyway…

**Comment by nhoizey** [comment]
Inspiration for the test suite:
https://github.com/aarongustafson/jekyll-webmention_io/tree/master/spec

**Comment by nhoizey** [comment]
Looks like tests are ok now
