### ISSUE TITLE
Does not work with GitHub pages

### ISSUE THREAD

**Issue by RicoSuter** [nhoizey/jekyll-postfiles#20]
Should this plugin work with GitHub pages (locally it works perfectly) or is this not supported?

**Comment by nhoizey** [comment]
GitHub Pages only work with a few plugins GitHub has selected. This one is not in the list unfortunately.

**Comment by DirtyF** [comment]
@RicoSuter I'd recommend to switch over https://netlify.com instead of Github Pages, to host your static sites for free. It has no limitation on Jekyll plugins 🎉

**Comment by RicoSuter** [comment]
I just migrated everything to GitHub Pages and this is my only problem now... I think your plugin is awesome and should be part of jekyll core or at least whitelisted for GH pages - I don't see how you could add images to a post in a way that it's rendered correctly on github directly and on the page...

**Comment by DirtyF** [comment]
As a core team member, I can tell you this plugin will not be part of core for now, neither will it make to Github Pages plugins, so hosting on Netlify instead of Github Pages is your only chance.

**Comment by nhoizey** [comment]
@RicoSuter you should read this: http://talk.jekyllrb.com/t/i-cannot-get-an-image-to-display/850/4

**Comment by RicoSuter** [comment]
@nhoizey yes, I now moved my images to /assets/posts/... and use absolute URLs in the markdown images - but now the markdown preview on GitHub directly and my local Visual Studio Code of course does not work anymore...

**Comment by nhoizey** [comment]
I agree it's one of the downsides of Jekyll's native support (or lack of) for images.

**Comment by RicoSuter** [comment]
Thanks - i now switched to netlify and it works as expected...

**Comment by hidegh** [comment]
@RicoSuter Plugin now works with on github pages via github action! See: https://jekyllrb.com/docs/continuous-integration/github-actions/

I used the CHIRPY theme, which automatically sets up github workflows, had just to rename master branch to main (due recent renames).
