### ISSUE TITLE
conflict with jekyll-relative-links

### ISSUE THREAD

**Issue by phoenixwu** [nhoizey/jekyll-postfiles#28]
[jekyll-relative-links](https://github.com/benbalter/jekyll-relative-links)
I used this plugin to easily generate relative links between .md files.
but it cannot co-work with jekyll-postfiles, I must disable it to let jekyll-postfiles works.

any suggestions?

**Comment by phoenixwu** [comment]
I changed _config.yml setting
`permalink: pretty`
into
`permalink: /:year-:month-:day-:title.html`

Both plugins can work together now.

**Comment by nhoizey** [comment]
@phoenixwu thanks for opening the issue. I see you reopened it. Does it mean your workaround finaly isn't enough?

**Comment by phoenixwu** [comment]
Oops, I accidentally reopened this issue. Sorry.
Changing permalink to `permalink: /:year-:month-:day-:title.html` is still working.
