### ISSUE TITLE
How to include plugin on a github.io site?

### ISSUE THREAD

**Issue by slcott** [nhoizey/jekyll-postfiles#3]
I would like to use the plugin on my github.io site. 

I have followed the instructions for installation and the local build of the site on my laptop works correctly. However, after I push the code update to my github repo I don't know it github.io is correctly installing the plugin. 

Can you help me?

**Comment by nhoizey** [comment]
There are just a few plugins that Github allows on Github Pages for auto generation:
https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

The only way to use Github Pages to host your site while using this plugin is to generate the pages HTML on your local host, and push it to your `gh-page` branch.
