### ISSUE TITLE
Does not work with Jekyll 4.0.0

### ISSUE THREAD

**Issue by contradictioned** [nhoizey/jekyll-postfiles#36]
Can't install together with Jekyll 4.0.0.
`bundle install` tells me:

```
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    jekyll-postfiles (~> 3.0.0) was resolved to 3.0.0, which depends on
      jekyll (~> 3.6)
```

**Comment by parsa20001999** [comment]
> Can't install together with Jekyll 4.0.0.
> `bundle install` tells me:
> 
> ```
> Bundler could not find compatible versions for gem "jekyll":
>   In snapshot (Gemfile.lock):
>     jekyll (= 4.0.0)
> 
>   In Gemfile:
>     jekyll-postfiles (~> 3.0.0) was resolved to 3.0.0, which depends on
>       jekyll (~> 3.6)
> ```
