### ISSUE TITLE
add option to automatically create subdirectories for postfiles

### ISSUE THREAD

**Issue by mohkale** [nhoizey/jekyll-postfiles#48]
The permalink for my posts is `/posts/:year/:month/:day/:title:output_ext`. Now if I have a posts directory like:

```yaml
- _posts/
  - 2019-06-19-foo.md
  - 2019-06-19-bar/
    - bar.js
    - assets/
      - main.png
```

I get a built posts directory like this:

```yaml
- _posts/
  - 2019/
    - 06/
      - 19/
        - foo.html
        - bar.html
        - bar.js
        - assets/
          - main.png
```

I can change the permalink to `/posts/:year/:month/:day/:title/` and then I get

```yaml
- _posts/
  - 2019/
    - 06/
      - 19/
        - foo/
          - index.html
        - bar/
          - index.html
          - bar.js
          - assets/
            - main.png
```

but I don't like the idea of a directory with only a single file (I.E. foo) so I propose we add an option in `jekyll-postfiles` where a directory is automatically created for a post if it has any postfiles (or exists in a subdirectory) such that:

```yaml
- _posts/
  - 2019/
    - 06/
      - 19/
        - foo.html
        - bar/
          - index.html
          - bar.js
          - assets/
            - main.png
```

**Comment by nhoizey** [comment]
Hi @mohkale, sorry for the veeeeery late answer, I don't use Jekyll anymore and I've been pretty lazy about my plugins… 😥

It looks like you want to have a dynamic permalink, with or without a folder, and I don't really like it:
- For users, I find it strange that permalinks would not be all the same.
- For this plugin, I fear this is a big change for something most users would not use anyway.

Do you think it would be possible to have another (new) plugin deal with the dynamic permalink, and `jekyll-postfiles` can "just" use the computed permalink?

**Comment by mohkale** [comment]
Actually I stopped using jekyll as well, and since opening this issue my opinion on this has matured as well. I agree in retrospect that this is a pretty terrible idea. For anyone whose curious why, see [Cool URIs don't change](https://www.w3.org/Provider/Style/URI).

In the meantime, I'm perfectly find with closing this issue now. ~~I'll remove this part from #49, there's still some features there that I belive should be in master so please continue to consider it.~~ Please still consider #47

**Comment by nhoizey** [comment]
@mohkale thanks! 🙏
