### ISSUE TITLE
postfiles aren't matched against converters?

### ISSUE THREAD

**Issue by mohkale** [nhoizey/jekyll-postfiles#51]
eg:

```yaml
- _posts
  - 2019-06-19-welcome-to-jekyll/
    - 2019-06-19-welcome-to-jekyll.md
    - assets/
      - main.scss
```

output files:

```
- _posts
  - 2019-06-19-welcome-to-jekyll/
    - index.html
    - assets/
      - main.scss
```

the sass file isn't converted to css before being included in the build directory.

**Comment by mohkale** [comment]
see also: [jekyll/renderer.rb](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/renderer.rb)

**Comment by DirtyF** [comment]
The original scope of the plugin was simply to gather images and markdown files in a single page bundle. I don't see the point of adding assets here though.

**Comment by mohkale** [comment]
I suppose your right. just felt like this would be a nice way to group styles you only intend to use on a single page.

**Comment by DirtyF** [comment]
Other methods like [CSS modules group files and styles](https://www.gatsbyjs.org/docs/css-modules/), but Jekylll users use Sass, and it's more usual to gather files through `@import` (or now `@use`).

**Comment by mohkale** [comment]
I suppose your right. I'll close this issue for now.
