### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/jekyll-postfiles#7]
Explain which files organizations can be used with this plugin

**Comment by heitorPB** [comment]
Would also be nice to have a note about GitHub compatibility: it took me a while to understand why the images were not appearing when github hosts, but works normally in a local installation...

**Comment by HamedJafarzadeh** [comment]
@heitorPB Can you explain more ? did you manage to solve it ?

**Comment by DirtyF** [comment]
This plugin is not supported by Github Pages, you have to host your site on services like https://netlify.com which support third party plugins.

**Comment by heitorPB** [comment]
@HamedJafarzadeh what I did was to use the plugin, but not the automatic GitHub build infrastructure.

I have two branches:
- `master` for the built site
- `src` for the jekyll files

I basically push the contentes of the `_site` folder to the master branch. More details [in this SO question](https://stackoverflow.com/questions/17835937/how-do-i-push-jekyll-site-directory-to-gh-pages-branch-and-leave-the-source-in).

@DirtyF, could you link this question in your PR as alternative to using and external service?

**Comment by DirtyF** [comment]
@heitorPB I won't but feel free to submit another PR.

Publishing your **build** in a versioned branch just to have it displayed on Github Pages is hackish, you can also use a third party CI service like Travis or Circle CI, but Netlify is the most accessible solution. Jekyll users shouldn't have to do these kind of circonvolutions to publish a site using plugins, so better go with a service that allows you to do so. As it comes with a free plan, that should be enough for most jekyll websites, and features like forms or support of GitLFS, image resizing, identity, etc. Netlify is to me the defacto web service to use when it comes to host static websites in 2019.

**Comment by heitorPB** [comment]
So, you don't want people to know there are alternatives to Netlify?

**Comment by DirtyF** [comment]
My point was more there are better alternatives than Github Pages in 2019. You can go with Now or whatever you like if you prefer. But as far as jekyll plugins are concerned, publishing on Github Pages is not straight forward.
